### ISSUE TITLE
SourceSet with name 'main' not found.

### ISSUE THREAD

**Issue by alexsurinov** [stepango/aar2jar#3]
I've got this error when I try to apply the latest version of the plugin to my kotlin gradle module:
```
SourceSet with name 'main' not found.
```
Log details:
```
Caused by: org.gradle.api.UnknownDomainObjectException: SourceSet with name 'main' not found.
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.createNotFoundException(DefaultNamedDomainObjectCollection.java:489)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:323)
	at org.gradle.kotlin.dsl.NamedDomainObjectCollectionExtensionsKt.get(NamedDomainObjectCollectionExtensions.kt:401)
	at com.stepango.aar2jar.Aar2Jar$apply$2.execute(Aar2Jar.kt:44)
	at com.stepango.aar2jar.Aar2Jar$apply$2.execute(Aar2Jar.kt:20)
	at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:41)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:97)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:94)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.configure(DefaultNamedDomainObjectCollection.java:886)
	at com.stepango.aar2jar.Aar2Jar.apply(Aar2Jar.kt:38)
	at com.stepango.aar2jar.Aar2Jar.apply(Aar2Jar.kt:20)
```
The gradle build script is:
```
plugins {
    id 'kotlin'
    id 'kotlin-kapt'
    id 'com.stepango.aar2jar' version "0.5"
}

dependencies {
    def dependencies = rootProject.ext.dependencies

    // Core app modules.
    implementation project(':core-di')

    // 3rd-party libs.
    implementation dependencies.kotlin
    implementation dependencies.rxJava
    compileOnlyAar dependencies.rxAndroid

    compileOnly androidJar

    // Kotlin annotation processors.
    kapt dependencies.daggerCompiler

    // Test libs.
    testImplementation dependencies.junit
}
```

**Comment by stepango** [comment]
@rAseri could you share the whole module sources, still can't reproduce your issue

here is the project with similar configuration https://github.com/stepango/Aar2Jar-playground, pls let me know if it helps.

**Comment by stepango** [comment]
Did some workaround, potentially should solve your issue try `v0.5.1`

**Comment by alexsurinov** [comment]
@stepango thank you! 
I've fixed the issue by adding ` classpath "gradle.plugin.com.stepango.aar2jar:aar2jar:0.5.1"` to the root gradle script and applying plugin to the kotlin gradle module (as in your playground project).

When I apply plugin in this way:
``` gradle
plugins {
    id 'kotlin'
    id 'kotlin-kapt'
    id 'com.stepango.aar2jar' version '0.5.1'
}
```
The issue `SourceSet with name 'main' not found` still appears.

**Comment by stepango** [comment]
Weird, both options should behave same way. Thanks for the clue, I'll continue to investigate this issue.
